service: include-functions

plugins:
  - serverless-ruby-layer

provider:
  name: aws
  runtime: ruby3.2

custom:
  rubyLayer:
    include_functions:
      - hello1
      - hello2

functions:
  hello1:
    handler: handler1.hello

  hello2:
    handler: handler2.hello

  hello3:
    handler: handler3.hello
