version: 2.1 

orbs:
  node: circleci/node@3

jobs:
  build-and-test:
    docker:
      - image: cimg/ruby:3.2-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - node/install-packages
      - run: sudo npm install -g serverless
      - run: sudo chown -R circleci:circleci /home/circleci/project/
      - run: sudo chown -R circleci:circleci  /usr/local/lib/node_modules/
      - run: npm test
      - run: npm run coverage

  deployment:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test

  deployment-workflow:
    jobs:

      - build-and-test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - deployment:
          requires:
            - build-and-test
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
