service: use-docker-with-environment

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    use_docker: true
    environment:
      - USE_HTTPARTY
      - NOKOGIRI_VERSION=1.13.10

provider:
  name: aws
  runtime: ruby3.2

functions:
  hello:
    handler: handler.hello
